### ISSUE TITLE
Missing Pronunciations in English dictionary

### ISSUE THREAD

**Issue by Setup2134** [yomidevs/kaikki-to-yomitan#155]
![image](https://github.com/user-attachments/assets/7edf975f-373a-4fe4-b5ad-40577c1a50f2)
Some pronunciations are missing in the english kaikki IPA dictionary. I don't know if it is just this word or there are other words with similar issues.
I believe that it might be because two country tags share the same pronunciation so it gets confused and only shows the pronunciation once and for the first country tag it finds

**Comment by StefanVukovic99** [comment]
Great catch, thanks! The same problem should now be fixed on other languages also.
