### ISSUE TITLE
IPA pronunciations for "Garage" in the german edition don't appear

### ISSUE THREAD

**Issue by emanuelps2708** [yomidevs/kaikki-to-yomitan#157]
Hi Ponfrit, sorry I bother, I just noticed this, it may happen because there are several pronunciations from different countries
https://de.wiktionary.org/wiki/Garage
![image](https://github.com/user-attachments/assets/3a7158b3-d4df-40e6-ad6c-0a3bccd95eb3)
![image](https://github.com/user-attachments/assets/d8cbdb08-5be0-445c-a567-7a1519d4f638)

**Comment by StefanVukovic99** [comment]
Opened https://github.com/tatuylonen/wiktextract/issues/930

**Comment by emanuelps2708** [comment]
I’m not sure if the fix for https://github.com/tatuylonen/wiktextract/issues/930 will resolve the issue, but I noticed that the entry 'Balkon' also doesn’t have any pronunciation. https://de.wiktionary.org/wiki/Balkon
![image](https://github.com/user-attachments/assets/326d1ced-7dec-44f4-aeb0-b21a1b14a923)
