### ISSUE TITLE
[Korean] label is in definition

### ISSUE THREAD

**Issue by bicolino34** [yomidevs/kaikki-to-yomitan#158]
In kty-ko-en dictionary word 독일 contains (South Korea) in definition, which I think is supposed to be a tag label. On English Wiktionary it is in the template {{lb}} which is for labels. 
![зображення](https://github.com/user-attachments/assets/fced83a8-0e8f-4852-9469-f7ee6e66aa95)

**Comment by StefanVukovic99** [comment]
![image](https://github.com/user-attachments/assets/f10507db-457b-4b72-9edb-303bc5b1ba0e)
Added it to tags, should make it into next release.
[kty-ko-en.zip](https://github.com/user-attachments/files/17603910/kty-ko-en.zip)
