### ISSUE TITLE
[Korean] label in definition

### ISSUE THREAD

**Issue by bicolino34** [yomidevs/kaikki-to-yomitan#159]
In the word 청소하다 there is (transitive) which should only be a tag. But it seems to be duplicated both as tag and a part of definition. Please, also check if intransitive is processed correctly.
![зображення](https://github.com/user-attachments/assets/a3ea8a0c-a908-444a-92a0-b28bc112a074)

**Comment by StefanVukovic99** [comment]
I think this should be fixed in the latest version (in [downloads](https://github.com/yomidevs/kaikki-to-yomitan/blob/master/downloads.md)).
