### ISSUE TITLE
missing example translations in en-es 

### ISSUE THREAD

**Issue by StefanVukovic99** [yomidevs/kaikki-to-yomitan#163]
Yeah, from what I've seen those spanish translations may be labeled `trad` (as in _traduccion_) so will need to write some specific handling to get them where available.

_Originally posted by @StefanVukovic99 in https://github.com/yomidevs/kaikki-to-yomitan/issues/83#issuecomment-2423175539_

**Comment by StefanVukovic99** [comment]
this should also be fixed now
@emanuelps2708

**Comment by emanuelps2708** [comment]
It works perfectly, thank you very much again for fixing this issue! 
![image](https://github.com/user-attachments/assets/725b0f42-2798-403e-b425-51345f04314f)
![image](https://github.com/user-attachments/assets/6eb37516-39e9-46dc-aecb-92b4816ead4a)
