### ISSUE TITLE
EN/PT-BR or NL/PT-BR

### ISSUE THREAD

**Issue by LiteralmenteoLucas** [yomidevs/kaikki-to-yomitan#164]
its almost impossible to find such a good dictionaries like that on internet to use with yomitan or some other dictionary tools linked with anki (anki connect) so im BEGGING please made one to help us to learn languages easily

**Comment by StefanVukovic99** [comment]
There's a small en-pt dict on the downloads page, we'll have to wait for kaikki.org to add the portuguese edition to get more.

**Comment by StefanVukovic99** [comment]
There is now also a small nl-pt dict on the downloads page.
