### ISSUE TITLE
Missing some definitions for the word "Neffe" (German wiktionary edition)

### ISSUE THREAD

**Issue by emanuelps2708** [yomidevs/kaikki-to-yomitan#169]
Hi Ponfrit, it appears that the entry Neffe currently doesn't have all the possible definitions (the most common one meaning nephew), it has some related to an insect at the moment. 
![image](https://github.com/user-attachments/assets/fe7b4239-088e-48a9-bbfe-d9330c3a0545)
https://de.wiktionary.org/wiki/Neffe
![image](https://github.com/user-attachments/assets/f7a0e795-9354-4622-b70d-481d3a2f294d)

**Comment by emanuelps2708** [comment]
I just noticed that the same 'error' occurs for the entry 'Rock.' https://de.wiktionary.org/wiki/Rock
![image](https://github.com/user-attachments/assets/421d553d-b78b-483d-8d02-d2536015e52b)

**Comment by emanuelps2708** [comment]
Sorry to bother you again, but this also seems to occur in the de-en (English) edition. For example, the entry 'Base' only includes the second meaning, not the 'main' one.
![image](https://github.com/user-attachments/assets/09ef09f6-c0d2-4347-afde-c2a1a6b7b258)
![image](https://github.com/user-attachments/assets/86bff81a-ef2d-4226-a89c-eb478eb43206)
https://en.wiktionary.org/wiki/Base#German

**Comment by StefanVukovic99** [comment]
I think we're currently getting only one etymology per part of speech, should be fixable.

**Comment by emanuelps2708** [comment]
It seems the issue has been fixed for the de-en edition—the entry 'Base' now includes the first definition. Thank you so much for resolving it!

Unfortunately, the issue still appears in the German and Spanish editions.
![image](https://github.com/user-attachments/assets/bacb617e-5b43-4acc-aa60-b81e319477e7)

**Comment by StefanVukovic99** [comment]
Should be fixed now

**Comment by emanuelps2708** [comment]
It works perfectly, thank you so much! 
![image](https://github.com/user-attachments/assets/583a16f5-bc26-4e17-b644-39ffaf6ced08)
