### ISSUE TITLE
Would be great to have ZH-VI dictionaries. 

### ISSUE THREAD

**Issue by cunat999** [yomidevs/kaikki-to-yomitan#174]
To study Chinese using English (which is not my native language) sometimes can be challenging. 
Thank you very much, Yomitan is awesome

**Comment by StefanVukovic99** [comment]
There's a small [zh-vi dict](https://github.com/yomidevs/kaikki-to-yomitan/releases/latest/download/kty-zh-vi-gloss.zip) in downloads, made from the translations section on the chinese edition of wiktionary. Vietnamese is not yet among the editions supported by [kaikki](https://kaikki.org/index.html) so we can't get more currently.

**Comment by cunat999** [comment]
Thank you!
