### ISSUE TITLE
Add example sentences

### ISSUE THREAD

**Issue by emanuelps2708** [yomidevs/kaikki-to-yomitan#83]
I think it might be super useful to have example sentences, most entries usually have one (from what I've seen from the German, English and Spanish editions, though the German edition appears to show examples differently).
![Screenshot from 2024-06-21 15-19-13](https://github.com/themoeway/kaikki-to-yomitan/assets/147004033/ff917b9a-a7c1-4b37-8a13-04c13afe86ff)
![Screenshot from 2024-06-21 15-27-19](https://github.com/themoeway/kaikki-to-yomitan/assets/147004033/8c5f15a2-5c18-4025-b1b4-13522a1fdcaa)
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/147004033/503a56be-b714-4980-9133-0c8e22fad5e7)
![image](https://github.com/themoeway/kaikki-to-yomitan/assets/147004033/931fa504-2d90-490c-9530-fbabb3d5e2c7)

**Comment by StefanVukovic99** [comment]
I'm working on this, right now it looks like:
![image](https://github.com/user-attachments/assets/6330c23d-0e6a-44d5-b95d-d7e1667423fe)
(i.e. like jitendex).

Currently, I've set it to filter out quotations, as they tend to be too long, and not easy to understand examples:
![image](https://github.com/user-attachments/assets/3aa90bda-2898-48f1-ab68-06563e3f9403) but maybe it should just have a character limit, like no examples over 70 chars.

The kaikki contains nothing to indicate which word in the example sentence should be highlighted. I could have it highlight at least when the headword is not inflected in the example, but this would probably be inconsistent/suboptimal. 

Maybe limit number of examples per sense to 1 (or 2)? Three may be too much here:
![image](https://github.com/user-attachments/assets/ae92322f-fe03-4b14-a910-1058ea693e40) The examples generally take up a lot of real-estate, which is part of the reason why I hadn't added them.

Italic might not be good for some languages?

Nested examples are missing right now (e.g. all the examples in https://en.wiktionary.org/wiki/gjuh%C3%AB#Albanian) , might add them, but I think they are a small percentage of cases.

If anyone wants to give it a go: 
[kty-de-en-example-sentences.zip](https://github.com/user-attachments/files/17385304/kty-de-en-example-sentences.zip)
I'll probably make a prerelease tomorrow so if anyone wants to test another language pair then that would be nice.

**Comment by emanuelps2708** [comment]
I just tested the de-en prerelease, it's amazing, thank you so much for your effort.
About maybe limiting the example sentences, I think a solution could be to set maximum 2 example sentences for each definition, and maybe add a link to the entry in the wiktionary webpage to check more info or examples (something like jitendex, it could be helpful for prepositions like "in" in German for example)
![image](https://github.com/user-attachments/assets/486407b3-c878-479a-9b66-8a4270cd5b68)
![image](https://github.com/user-attachments/assets/15d93116-bd9c-4abb-a780-b4eb34f40d52)
Also it would be great if at some time the entry word could be highlighted or bolded, I think that could make it more readable, besides that it's great, thank you so much again ;)

**Comment by StefanVukovic99** [comment]
For en-es `read`, AFAICT, the first example is getting filtered out because it is too long, and the others are missing in the kaikki data so i opened [an issue](https://github.com/tatuylonen/wiktextract/issues/880).

**Comment by emanuelps2708** [comment]
Ohhh ok ponfrit, thank you ;)

**Comment by emanuelps2708** [comment]
Ponfrit Upon further checking, it seems the English-Spanish edition includes most example sentences, but it appears to lack translations for some words, such as 'car' and 'fast.
![image](https://github.com/user-attachments/assets/79a8e51b-21f7-41b1-887c-2606e3052a2a)
![image](https://github.com/user-attachments/assets/ebedf8be-0252-4b7b-bc92-0b04a752f355)
![image](https://github.com/user-attachments/assets/22e701d6-7ba9-47ed-94ca-98370ea13de8)
![image](https://github.com/user-attachments/assets/79f4e349-c75f-44d5-82b2-d89303807764)

**Comment by StefanVukovic99** [comment]
Yeah, from what I've seen those spanish translations may be labeled `trad` (as in _traduccion_) so will need to write some specific handling to get them where available.

**Comment by PIPPOHSIOS** [comment]
Is there a way to hide or disable the example sentences?

**Comment by StefanVukovic99** [comment]
You might add something like
```css
[data-dictionary^="kty"] [data-sc-content="example-sentence"]{
    display: none;
}
```
to your custom CSS.

**Comment by PIPPOHSIOS** [comment]
It works, thank you!

**Comment by PIPPOHSIOS** [comment]
Sorry to disturb you again, when I added a new note I noticed that also the example sentences were written along the definitions. Is there a way to avoid this?
